'use strict';

// tests for getQuotes
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getQuotes', '/handler.ts', 'getQuotes');

describe('getQuotes', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({
      pathParameters: {
        symbol: 'XYZ'
      }
    }).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
